insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 359256898);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 159485042);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 177253266);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 189784706);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 129762509);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 205364791);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 261303137);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 164109908);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 393398783);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 294824888);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 325044087);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 351498063);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 256775146);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 191615896);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 220905890);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 360989679);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 339491019);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 318259514);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 329844805);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 385659189);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 109619014);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 211713624);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 233137829);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 380140853);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 315338372);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 283811199);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 281270799);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 294823843);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 232869937);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 241136257);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 359694172);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 181668049);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 310617063);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 283943319);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 361773162);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 185664104);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 146479897);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 398933778);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 136906412);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 190329966);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 135895902);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 310735132);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 308529959);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 149279165);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 211568776);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 226422703);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 252719579);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 358439710);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 269492380);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 333935953);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 367412892);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 210068084);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 324338486);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 332608861);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 227517155);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 251805408);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 223289556);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 351026039);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 157162303);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 153741075);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 245700245);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 211304171);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 260470025);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 330319362);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 111101992);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 374911960);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 260473890);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 281273510);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 192883321);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 163989043);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 371930470);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 190416590);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 336922518);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 101124297);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 174051016);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 333968154);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 156589827);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 127193813);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 392219485);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 226772485);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 115314022);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 336912862);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 304097784);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 177100687);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 151447272);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 250427777);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 390526351);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 182718298);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 264661698);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 147326938);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 289849149);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 188852848);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 201751074);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 353007809);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 249576131);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 199177663);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 243238971);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 348382755);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 397538066);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 377357435);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 262009243);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 213677469);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 244592440);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 297253057);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 212690715);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 312299024);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 397423821);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 189780739);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 239875922);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 327240102);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 165695583);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 168383962);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 145652280);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 263482415);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 217816801);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 373629449);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 363971320);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 386147203);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 220367403);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 100145462);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 148163497);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 143117034);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 283464548);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 375223953);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 112667225);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 102267244);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 157986385);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 110547052);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 319438714);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 184481366);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 212585582);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tadmor', 154555237);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 148224820);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 144754453);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 318134765);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 343156773);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 170806075);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 387235647);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 282844184);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 263150568);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 143368504);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Academy', 244185113);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 168584386);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 220674927);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 240666212);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Israel School of Bartending', 241257262);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 200183884);
insert into Bartender_academic_institution (academic_institution, person_id) values ('The Brown School of Mixology', 107994561);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 374407863);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 137268428);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 115638044);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 229440804);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bar Master', 238055827);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 223548523);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 362953183);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Zman Amiti', 179522835);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Tapuz Bartending School', 197731117);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Bishulim Culinary School', 288191866);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Taste Academy', 102371805);
insert into Bartender_academic_institution (academic_institution, person_id) values ('Danon Culinary School', 290543190);
